apiVersion: v1
kind: Service
metadata:
  name: ecommerce-api-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: ecommerce-api
  ports:
  - name: app
    port: 6000
    targetPort: 6000
  - name: gateway
    port: 6001
    targetPort: 6001